# Generated by Django 5.2.6 on 2025-10-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0002_initial'),
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='clinica',
        ),
        migrations.AddField(
            model_name='medico',
            name='clinicas',
            field=models.ManyToManyField(blank=True, related_name='medicos', to='clinicas.clinica'),
        ),
    ]
