# Generated by Django 5.2.6 on 2025-11-02 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='clinica',
        ),
    ]
