# Generated by Django 5.2.6 on 2025-11-17 11:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0002_remove_medico_clinica_medico_clinicas'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='valor_consulta',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Valor da Consulta Padrão'),
        ),
    ]
