# Generated by Django 5.2.6 on 2025-11-02 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0002_initial'),
        ('medicos', '0002_remove_medico_clinica'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicos', to='clinicas.clinica'),
        ),
    ]
