# Generated by Django 5.2.6 on 2025-10-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_remove_paciente_dados_clinicos_paciente_altura_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='cep',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
    ]
