# Generated by Django 5.2.6 on 2025-11-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='remarcacoes_paciente',
            field=models.PositiveIntegerField(default=0, verbose_name='Nº de Remarcações pelo Paciente'),
        ),
    ]
